/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                   '#95d3ba',
        'on-primary':                '#003829',
        'primary-container':         '#064e3b',
        'on-primary-container':      '#80bea6',
        'secondary':                 '#F9F1D0',
        'on-secondary':              '#3c2f00',
        'secondary-container':       '#af8d11',
        'surface':                   '#131313',
        'surface-dim':               '#0e0e0e',
        'surface-bright':            '#393939',
        'surface-container':         '#201f1f',
        'surface-container-low':     '#1c1b1b',
        'surface-container-high':    '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface':                '#e5e2e1',
        'on-surface-variant':        '#bfc9c3',
        'outline':                   '#89938d',
        'outline-variant':           '#404944',
        'background':                '#131313',
        'on-background':             '#e5e2e1',
        'error':                     '#ffb4ab',
        'on-error':                  '#690005',
        'success':                   '#10b981',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        body:    ['Inter', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        'md':    '0.75rem',
        'lg':    '1rem',
        'xl':    '1.5rem',
        'full':  '9999px',
      },
      spacing: {
        'xs':             '4px',
        'sm':             '12px',
        'base':           '8px',
        'md':             '24px',
        'lg':             '48px',
        'xl':             '80px',
        'gutter':         '24px',
        'margin-mobile':  '16px',
        'margin-desktop': '64px',
      },
    },
  },
  plugins: [],
}